### ISSUE TITLE
[auto-generated:-485907966] de.halirutan.mathematica.lang.psi.impl.StringifiedSymbolImpl cannot be cast to de.halirutan.mathematica.lang.psi.api.Symbol

### ISSUE THREAD

**Issue by Mathematica-IntelliJ-Plugin** [Mathematica-IntelliJ-Plugin/Auto-generated-issues-for-the-Mathematica-Plugin#50]
- Plugin Name: Mathematica Support
- Plugin Version: 3.0pre12
- OS Name: Mac OS X
- Java version: 1.8.0_152-release
- Java vm vendor: JetBrains s.r.o
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version name: IntelliJ IDEA
- Is EAP: false
- App Build: IU-181.4668.68
- App Version: 2018.1.2
- Last Action: EditorBackSpace

```
java.lang.ClassCastException: de.halirutan.mathematica.lang.psi.impl.StringifiedSymbolImpl cannot be cast to de.halirutan.mathematica.lang.psi.api.Symbol
	at de.halirutan.mathematica.codeinsight.completion.providers.ImportedSymbolCompletion.addCompletions(ImportedSymbolCompletion.java:62)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:143)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:149)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:90)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:143)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:116)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:797)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:293)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:290)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by szhorvat** [comment]
When this happened, I messed up the matching of opening-closing brackets. I can't trigger the problem a second time though. Here's a screenshot of what the code looked like shortly after the error (it has a few extra edits).  Notice the red colouring on a bracket. This is because there's one bracket too many.

![image](https://user-images.githubusercontent.com/1212871/39697964-288f10e0-51f3-11e8-89dc-a20ead70f8f3.png)

It says that "The last expression could not be parsed correctly."

**Comment by halirutan** [comment]
@szhorvat Please don't bother. I had a hard cast in there that expected a Symbol but what I was getting is a stringified symbol like the `invopt` in `IGCliqueCover::invopt`. I simply replaced the cast with a test for the correct class and this issue should no longer appear.
